//! Floating AI Copilot & Fixer interactive modal dialog.
//!
//! Provides inline prompt generation, smart code/text fixing, tab completion,
//! and live markdown/code proposal previews with 1-key accept & replace.

use crate::ai::{self, AiAction, AiRequest, AiResult, AiSettings};
use crate::app::QuickyNotesApp;
use crate::components::button;
use crate::components::card;
use crate::theme::{self, Palette};
use eframe::egui::{self, Color32, CornerRadius, FontId, Key, Margin, RichText, Sense, Stroke, Ui};
use std::sync::mpsc;

/// Ephemeral state for the floating AI Copilot modal overlay.
#[derive(Default)]
pub struct AiModalState {
    /// Whether the AI Copilot dialog is currently visible.
    pub is_open: bool,

    /// Character range `(start_idx, end_idx)` in active note to replace on accept.
    /// If `None`, AI response will be inserted at cursor / appended.
    pub target_range: Option<(usize, usize)>,

    /// Raw text selected by the user.
    pub target_text: String,

    /// Context lines preceding the cursor for smarter completions.
    pub context_before: String,

    /// User-entered custom instruction in the modal's input field.
    pub custom_prompt: String,

    /// Proposed text generated by the AI backend.
    pub preview_result: Option<String>,

    /// Last error message if request failed.
    pub error_msg: Option<String>,

    /// Whether an AI generation task is currently in flight.
    pub is_loading: bool,

    /// Trigger flag to focus the prompt input field on first open.
    pub focus_input: bool,

    /// Receiver for async AI completion results.
    pub active_rx: Option<mpsc::Receiver<AiResult>>,
}

impl AiModalState {
    /// Opens the AI Copilot modal with target text selection and preceding context.
    pub fn open(
        &mut self,
        target_range: Option<(usize, usize)>,
        target_text: String,
        context_before: String,
    ) {
        self.is_open = true;
        self.target_range = target_range;
        self.target_text = target_text;
        self.context_before = context_before;
        self.custom_prompt.clear();
        self.preview_result = None;
        self.error_msg = None;
        self.focus_input = true;
        self.is_loading = false;
        self.active_rx = None;
    }

    /// Closes the modal and resets in-flight state.
    pub fn close(&mut self) {
        self.is_open = false;
        self.is_loading = false;
        self.active_rx = None;
        self.preview_result = None;
        self.error_msg = None;
        self.custom_prompt.clear();
        self.target_range = None;
        self.target_text.clear();
        self.context_before.clear();
    }

    /// Dispatches an AI request asynchronously using current settings.
    pub fn trigger_action(&mut self, ai_settings: &AiSettings, action: AiAction) {
        self.is_loading = true;
        self.error_msg = None;
        self.preview_result = None;

        let req = AiRequest {
            target_text: self.target_text.clone(),
            context_before: self.context_before.clone(),
            action,
            provider: ai_settings.provider,
            model: ai_settings.model.clone(),
            api_key: ai_settings.api_key.clone(),
            system_prompt: ai_settings.system_prompt.clone(),
        };

        let rx = ai::spawn_ai_request(req);
        self.active_rx = Some(rx);
    }

    /// Polls the background channel for completed AI tasks.
    pub fn poll_results(&mut self) {
        if let Some(rx) = &self.active_rx
            && let Ok(result) = rx.try_recv()
        {
            self.is_loading = false;
            self.active_rx = None;
            match result {
                AiResult::Success { result_text, .. } => {
                    self.preview_result = Some(result_text);
                    self.error_msg = None;
                }
                AiResult::Error(err) => {
                    self.preview_result = None;
                    self.error_msg = Some(err);
                }
            }
        }
    }
}

/// Extracts text selection and surrounding context from active note and launches AI Copilot modal.
pub fn launch_copilot(app: &mut QuickyNotesApp) {
    if !app.data.settings.ai.enabled {
        app.show_toast(
            "AI Assistant is disabled in settings",
            crate::ui::toast::ToastKind::Warning,
        );
        return;
    }

    let Some(active_id) = app.data.active_note_id.clone() else {
        app.show_toast(
            "No active note open for AI assist",
            crate::ui::toast::ToastKind::Warning,
        );
        return;
    };

    let Some(note) = app.data.notes.iter().find(|n| n.id == active_id) else {
        return;
    };

    let (range, target_text, context_before) = if let Some((start, end)) = app.last_cursor_range {
        let total_chars = note.char_len();
        let s = start.min(total_chars);
        let e = end.min(total_chars).max(s);
        if s < e {
            let selected = note.char_slice(s, e);
            let ctx_before: String = note
                .char_slice(0, s)
                .chars()
                .rev()
                .take(400)
                .collect::<String>()
                .chars()
                .rev()
                .collect();
            (Some((s, e)), selected, ctx_before)
        } else {
            let ctx_before: String = note
                .char_slice(0, s)
                .chars()
                .rev()
                .take(600)
                .collect::<String>()
                .chars()
                .rev()
                .collect();
            (None, String::new(), ctx_before)
        }
    } else {
        let ctx_before: String = note
            .content
            .chars()
            .rev()
            .take(600)
            .collect::<String>()
            .chars()
            .rev()
            .collect();
        (None, String::new(), ctx_before)
    };

    app.ai_modal.open(range, target_text, context_before);
}

/// Renders the floating AI Copilot modal dialog overlay.
pub fn render_ai_copilot_modal(app: &mut QuickyNotesApp, ctx: &egui::Context) {
    app.ai_modal.poll_results();

    if !app.ai_modal.is_open {
        return;
    }

    let palette = theme::get_palette(&app.data.settings);
    let mut accept_triggered = false;
    let mut discard_triggered = false;
    let mut copy_triggered = false;
    let mut action_to_trigger = None;

    // Handle global keyboard shortcuts while modal is open
    if ctx.input(|i| i.key_pressed(Key::Escape)) {
        discard_triggered = true;
    }

    if app.ai_modal.preview_result.is_some()
        && ctx.input(|i| i.key_pressed(Key::Tab) || (i.modifiers.ctrl && i.key_pressed(Key::Enter)))
    {
        accept_triggered = true;
    }

    // 1. Translucent backdrop dimmer rendered via layer painter
    let screen_rect = ctx.content_rect();
    let modal_width = (screen_rect.width() - 32.0).clamp(280.0, 720.0);
    let modal_pos = egui::pos2(
        (screen_rect.center().x - modal_width / 2.0).max(screen_rect.min.x + 16.0),
        (screen_rect.min.y + 30.0).max(screen_rect.center().y - 200.0),
    );

    ctx.layer_painter(egui::LayerId::new(
        egui::Order::Foreground,
        egui::Id::new("ai_copilot_backdrop"),
    ))
    .rect_filled(
        screen_rect,
        CornerRadius::ZERO,
        Color32::from_rgba_unmultiplied(0, 0, 0, 50),
    );

    let mut modal_rect = egui::Rect::from_min_size(modal_pos, egui::vec2(modal_width, 240.0));

    // 2. Centered Glass Modal Dialog Card
    egui::Area::new(egui::Id::new("ai_copilot_modal_card"))
        .order(egui::Order::Tooltip)
        .fixed_pos(modal_pos)
        .show(ctx, |ui| {
            ui.set_width(modal_width);
            let frame_resp = egui::Frame::NONE
                .fill(Color32::from_rgba_unmultiplied(
                    palette.card.r(),
                    palette.card.g(),
                    palette.card.b(),
                    250,
                ))
                .stroke(Stroke::new(1.5, palette.accent))
                .corner_radius(CornerRadius::same(14))
                .inner_margin(Margin::symmetric(16, 14))
                .shadow(egui::Shadow {
                    offset: [0, 8],
                    blur: 24,
                    spread: 2,
                    color: Color32::from_black_alpha(80),
                })
                .show(ui, |ui| {
                    ui.vertical(|ui| {
                        // 1. Header with model badge & compact ✕ close button
                        ui.horizontal(|ui| {
                            ui.spacing_mut().item_spacing.x = 8.0;
                            ui.label(
                                RichText::new("AI Copilot")
                                    .font(FontId::proportional(15.0))
                                    .strong()
                                    .color(Color32::WHITE),
                            );

                            let active_model = if app.data.settings.ai.model.trim().is_empty() {
                                app.data.settings.ai.provider.default_model()
                            } else {
                                &app.data.settings.ai.model
                            };

                            let badge_bg = Palette::with_alpha(palette.accent, 40);
                            let (badge_rect, _) = ui.allocate_exact_size(
                                egui::vec2(active_model.len() as f32 * 7.2 + 14.0, 20.0),
                                Sense::hover(),
                            );
                            ui.painter()
                                .rect_filled(badge_rect, CornerRadius::same(10), badge_bg);
                            ui.painter().rect_stroke(
                                badge_rect,
                                CornerRadius::same(10),
                                Stroke::new(1.0, Palette::with_alpha(palette.accent, 120)),
                                egui::StrokeKind::Outside,
                            );
                            ui.painter().text(
                                badge_rect.center(),
                                egui::Align2::CENTER_CENTER,
                                active_model,
                                FontId::monospace(10.5),
                                palette.accent,
                            );

                            ui.with_layout(
                                egui::Layout::right_to_left(egui::Align::Center),
                                |ui| {
                                    let close_btn = button::icon_button(
                                        ui,
                                        "✕",
                                        false,
                                        &palette,
                                        13.0,
                                        egui::vec2(26.0, 26.0),
                                    );
                                    if close_btn.on_hover_text("Close (Esc)").clicked() {
                                        discard_triggered = true;
                                    }
                                },
                            );
                        });

                        ui.add_space(6.0);

                        // 2. Selection Context Indicator
                        let context_info = if !app.ai_modal.target_text.is_empty() {
                            let preview_snippet = if app.ai_modal.target_text.len() > 30 {
                                format!("{}...", &app.ai_modal.target_text[..30])
                            } else {
                                app.ai_modal.target_text.clone()
                            };
                            format!(
                                "Target Selection ({} chars): \"{}\"",
                                app.ai_modal.target_text.len(),
                                preview_snippet.replace('\n', " ")
                            )
                        } else {
                            "Cursor Mode: Continue from active cursor position".to_string()
                        };

                        ui.label(
                            RichText::new(context_info)
                                .font(FontId::proportional(11.0))
                                .color(Color32::from_gray(175)),
                        );

                        ui.add_space(8.0);

                        // 3. Quick Action Preset Tiles
                        ui.horizontal_wrapped(|ui| {
                            ui.spacing_mut().item_spacing = egui::vec2(6.0, 6.0);

                            if render_action_tile(ui, "Fix & Polish", &palette).clicked() {
                                action_to_trigger = Some(AiAction::FixAndPolish);
                            }

                            if render_action_tile(ui, "Complete", &palette).clicked() {
                                action_to_trigger = Some(AiAction::Complete);
                            }

                            if render_action_tile(ui, "Summarize", &palette).clicked() {
                                action_to_trigger = Some(AiAction::Summarize);
                            }

                            if render_action_tile(ui, "Explain", &palette).clicked() {
                                action_to_trigger = Some(AiAction::Explain);
                            }
                        });

                        ui.add_space(10.0);

                        // 4. Custom Prompt Input Row (Fluid width)
                        ui.horizontal(|ui| {
                            ui.spacing_mut().item_spacing.x = 6.0;

                            let btn_width = 72.0;
                            let prompt_width = (ui.available_width() - btn_width - 6.0).max(100.0);
                            let prompt_edit = egui::TextEdit::singleline(
                                &mut app.ai_modal.custom_prompt,
                            )
                            .hint_text(
                                "Ask AI anything (e.g. 'Convert to Python', 'Make concise')...",
                            )
                            .font(FontId::proportional(12.5))
                            .desired_width(prompt_width)
                            .margin(Margin::symmetric(10, 8));

                            let resp = ui.add(prompt_edit);
                            if app.ai_modal.focus_input {
                                resp.request_focus();
                                app.ai_modal.focus_input = false;
                            }

                            // Automatically trigger Run when Enter key is pressed in Copilot block
                            let enter_pressed = ctx.input(|i| i.key_pressed(Key::Enter));
                            if enter_pressed && !app.ai_modal.is_loading {
                                ctx.input_mut(|i| i.consume_key(egui::Modifiers::NONE, Key::Enter));
                                if !app.ai_modal.custom_prompt.trim().is_empty() {
                                    action_to_trigger =
                                        Some(AiAction::Custom(app.ai_modal.custom_prompt.clone()));
                                } else if app.ai_modal.target_range.is_some() {
                                    action_to_trigger = Some(AiAction::FixAndPolish);
                                } else {
                                    action_to_trigger = Some(AiAction::Complete);
                                }
                            }

                            let can_run = !app.ai_modal.is_loading;
                            let run_btn = button::animated_primary_button(
                                ui,
                                "Run ↵",
                                &palette,
                                egui::vec2(btn_width, 32.0),
                            );
                            if run_btn.clicked() && can_run {
                                if !app.ai_modal.custom_prompt.trim().is_empty() {
                                    action_to_trigger =
                                        Some(AiAction::Custom(app.ai_modal.custom_prompt.clone()));
                                } else if app.ai_modal.target_range.is_some() {
                                    action_to_trigger = Some(AiAction::FixAndPolish);
                                } else {
                                    action_to_trigger = Some(AiAction::Complete);
                                }
                            }
                        });

                        // 5. Loading Spinner, Error, or Preview Area
                        if app.ai_modal.is_loading {
                            ui.add_space(14.0);
                            ui.horizontal(|ui| {
                                ui.spacing_mut().item_spacing.x = 8.0;
                                ui.spinner();
                                ui.label(
                                    RichText::new("Generating AI proposal...")
                                        .font(FontId::proportional(12.5))
                                        .color(palette.accent),
                                );
                            });
                            ctx.request_repaint();
                        } else if let Some(err) = &app.ai_modal.error_msg {
                            ui.add_space(10.0);
                            card::settings_card(ui, "AI ERROR", &palette, |ui| {
                                ui.label(
                                    RichText::new(format!("Error: {}", err))
                                        .font(FontId::proportional(12.0))
                                        .color(Color32::from_rgb(239, 68, 68)),
                                );
                            });
                        } else if let Some(preview) = &app.ai_modal.preview_result {
                            ui.add_space(12.0);
                            ui.label(
                                RichText::new("AI PROPOSAL:")
                                    .font(FontId::proportional(11.0))
                                    .strong()
                                    .color(palette.accent),
                            );
                            ui.add_space(4.0);

                            // Scrollable diff / preview box with responsive height and width
                            let max_preview_height =
                                (screen_rect.height() * 0.45).clamp(100.0, 320.0);
                            egui::ScrollArea::vertical()
                                .id_salt("ai_preview_scroll")
                                .max_height(max_preview_height)
                                .auto_shrink([false, false])
                                .show(ui, |ui| {
                                    ui.set_width(ui.available_width());
                                    let preview_frame = egui::Frame::NONE
                                        .fill(Color32::from_rgba_unmultiplied(20, 15, 30, 220))
                                        .stroke(Stroke::new(1.0, palette.border))
                                        .corner_radius(CornerRadius::same(6))
                                        .inner_margin(Margin::same(10));

                                    preview_frame.show(ui, |ui| {
                                        ui.set_width(ui.available_width());
                                        ui.add(
                                            egui::Label::new(
                                                RichText::new(preview)
                                                    .font(FontId::monospace(12.0))
                                                    .color(Color32::from_rgb(230, 235, 245)),
                                            )
                                            .wrap(),
                                        );
                                    });
                                });

                            ui.add_space(12.0);

                            // 6. Action Buttons Bar (Responsive wrapped layout)
                            ui.horizontal_wrapped(|ui| {
                                ui.spacing_mut().item_spacing = egui::vec2(8.0, 6.0);

                                let accept_btn = button::animated_primary_button(
                                    ui,
                                    "Accept (Tab)",
                                    &palette,
                                    egui::vec2(110.0, 32.0),
                                );
                                if accept_btn.clicked() {
                                    accept_triggered = true;
                                }

                                let copy_btn = button::animated_action_button(
                                    ui,
                                    "Copy",
                                    &palette,
                                    egui::vec2(70.0, 32.0),
                                );
                                if copy_btn.clicked() {
                                    ui.ctx().copy_text(preview.clone());
                                    copy_triggered = true;
                                }

                                let discard_btn = button::animated_danger_button(
                                    ui,
                                    "Discard (Esc)",
                                    egui::vec2(100.0, 32.0),
                                );
                                if discard_btn.clicked() {
                                    discard_triggered = true;
                                }
                            });
                        }
                    });
                });
            modal_rect = frame_resp.response.rect;
        });

    // Dismiss only if clicked strictly outside the modal card bounds
    if ctx.input(|i| i.pointer.button_clicked(egui::PointerButton::Primary))
        && let Some(pos) = ctx.input(|i| i.pointer.interact_pos())
        && !modal_rect.expand(6.0).contains(pos)
    {
        discard_triggered = true;
    }

    if copy_triggered {
        app.show_toast(
            "Copied AI proposal to clipboard ✓",
            crate::ui::toast::ToastKind::Success,
        );
    }

    if let Some(action) = action_to_trigger {
        let ai_settings = app.data.settings.ai.clone();
        app.ai_modal.trigger_action(&ai_settings, action);
        ctx.request_repaint();
    }

    if accept_triggered {
        if let Some(preview_text) = app.ai_modal.preview_result.clone() {
            apply_ai_replacement(app, &preview_text);
        }
        app.ai_modal.close();
        app.focus_editor = true;
        ctx.request_repaint();
    }

    if discard_triggered {
        app.ai_modal.close();
        app.focus_editor = true;
        ctx.request_repaint();
    }
}

/// Applies the accepted AI text back into the active note.
fn apply_ai_replacement(app: &mut QuickyNotesApp, replacement: &str) {
    if let Some(active_id) = app.data.active_note_id.clone()
        && let Some(note) = app.data.notes.iter_mut().find(|n| n.id == active_id)
    {
        if let Some((start, end)) = app.ai_modal.target_range {
            note.replace_char_range(start, end, replacement);
            app.is_dirty = true;
            app.show_toast("AI changes applied ✓", crate::ui::toast::ToastKind::Success);
        } else {
            // Append or insert
            if !note.content.is_empty() && !note.content.ends_with('\n') {
                note.content.push('\n');
            }
            note.content.push_str(replacement);
            note.update_timestamp();
            app.is_dirty = true;
            app.show_toast(
                "AI completion inserted ✓",
                crate::ui::toast::ToastKind::Success,
            );
        }
    }
}

/// Renders a quick action preset tile button with clean typography and hover animation.
fn render_action_tile(ui: &mut Ui, label: &str, palette: &Palette) -> egui::Response {
    let font = FontId::proportional(12.0);
    let label_galley = ui
        .painter()
        .layout_no_wrap(label.to_string(), font.clone(), Color32::WHITE);

    let total_width = label_galley.size().x + 22.0;
    let height = 28.0;

    let (rect, response) = ui.allocate_exact_size(egui::vec2(total_width, height), Sense::click());
    let is_hovered = response.hovered();
    let hov_anim = ui
        .ctx()
        .animate_bool_responsive(response.id.with("tile_hov"), is_hovered);

    let base_bg = Palette::with_alpha(palette.card, 220);
    let hover_bg = Palette::interpolate_color(base_bg, palette.accent, 0.25);
    let bg = Palette::interpolate_color(base_bg, hover_bg, hov_anim);

    let border_color = Palette::interpolate_color(
        Palette::with_alpha(palette.border, 160),
        palette.accent,
        hov_anim,
    );

    ui.painter().rect_filled(rect, CornerRadius::same(6), bg);
    ui.painter().rect_stroke(
        rect,
        CornerRadius::same(6),
        Stroke::new(1.0 + 0.5 * hov_anim, border_color),
        egui::StrokeKind::Outside,
    );

    let text_color = if is_hovered {
        Color32::WHITE
    } else {
        Color32::from_gray(225)
    };
    ui.painter().text(
        rect.center(),
        egui::Align2::CENTER_CENTER,
        label,
        font,
        text_color,
    );

    response
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ai_modal_state_open_and_close() {
        let mut state = AiModalState::default();
        assert!(!state.is_open);

        state.open(
            Some((5, 15)),
            "selected text".to_string(),
            "preceding context".to_string(),
        );
        assert!(state.is_open);
        assert_eq!(state.target_range, Some((5, 15)));
        assert_eq!(state.target_text, "selected text");
        assert_eq!(state.context_before, "preceding context");
        assert!(state.focus_input);

        state.close();
        assert!(!state.is_open);
        assert!(state.target_range.is_none());
        assert!(state.target_text.is_empty());
        assert!(state.context_before.is_empty());
    }

    #[test]
    fn test_ai_modal_state_poll_results() {
        let mut state = AiModalState::default();
        let (tx, rx) = mpsc::channel();
        state.active_rx = Some(rx);
        state.is_loading = true;

        tx.send(AiResult::Success {
            original_text: "bad code".to_string(),
            action: AiAction::FixAndPolish,
            result_text: "fixed code".to_string(),
        })
        .unwrap();

        state.poll_results();
        assert!(!state.is_loading);
        assert_eq!(state.preview_result, Some("fixed code".to_string()));
        assert!(state.error_msg.is_none());
    }
}
